### ISSUE TITLE
Using querystringparser

### ISSUE THREAD

**Issue by tjconcept** [petkaantonov/urlparser#10]
I noted that you are using the `querystring` module and not you own `querystringparser` (when I tried to use this with a nested object), and I'm just curious about why it is so? Is it to keep it a drop-in-replacement of `url`?

**Comment by mikeal** [comment]
> What a shame - we might see more from io.js.

Are there any API breaks? I can't imagine any reason a 30x perf improvement would be rejected provided it doesn't break or change API :)

**Comment by petkaantonov** [comment]
> Are there any API breaks? I can't imagine any reason a 30x perf improvement would be rejected provided it doesn't break or change API :)

It depends if you consider the implementation of a property as part of the API (data property or getter)

**Comment by mikeal** [comment]
There's more than one issue swirling around about this so I already made this comment somewhere else but: can't we lazily produce identical output to the current API on stringify/jsonify and iterable? We can eat the perf hit when people touch these edge cases without losing the perf benefits of this approach.

**Comment by petkaantonov** [comment]
Sure you can define a `toJSON` method that emulates the output that an eagerly parsed url object would give. JSON.stringify implicitly calls it.

**Comment by mikeal** [comment]
Would we still have iterable issues? I haven't gotten deep enough in to property access guts to know if that will also be an issue but I'm pretty sure that we have a way to emulate it now in ES6.

**Comment by petkaantonov** [comment]
The getters are currently not enumerable (that is of course trivial to change) but even after changing them to enumerable, they are still on the prototype and not on the object itself which trips up stuff like `._extend`.

**Comment by jedwards1211** [comment]
@petkaantonov 
> It's because this is supposed to be rewrite of the url module and be integrated into node core

Just curious, did it ever get merged into node core?
